imi-ms/MoPat

pom.xml

Updated CDISC ODM Version

---

src/main/java/de/imi/mopat/controller/QuestionnaireController.java

Added check to import MoPats ODM format

---

src/main/java/de/imi/mopat/controller/ConfigurationController.java

Utilized dependency injection in ConfigurationController to trigger MailSender update method

#25: Implemented automatic mail system updates

---

pom.xml

Replaced jakarta activation with angus activation

---

src/main/webapp/WEB-INF/mobile/user/password.html

Added correct class to password request button

---

src/main/webapp/WEB-INF/mapping/map.html

Adjusted template to fix REDCap mapping errors

---

src/main/webapp/WEB-INF/question/edit.html

Adjusted icons to use chevron-double icons

---

pom.xml
src/main/webapp/WEB-INF/mapping/map.html
src/main/webapp/WEB-INF/mobile/user/password.html
src/main/webapp/WEB-INF/question/edit.html

Hotfixes for #58, #59, #60, #65

MoPat v3.1.2

---

src/main/webapp/WEB-INF/bundle/edit.html
src/main/webapp/WEB-INF/clinic/edit.html
src/main/webapp/WEB-INF/mobile/user/password.html

Implemented structural changes to accomodate easy automated tests

Selenium automation tests for mopat flows

---

pom.xml
src/main/java/de/imi/mopat/cron/EncounterScheduledExecutor.java

Release version 3.1.4

---

src/main/java/de/imi/mopat/controller/BundleController.java

Added check to only fetch questionnaires with scores if any are available

---

src/main/java/de/imi/mopat/io/impl/EncounterExporterTemplateHL7v2.java

Added check to port conversion, so that the error is caught

---

src/main/java/de/imi/mopat/controller/EncounterController.java

Added month and year to check if a mail should be send out

---

db/update/v3.2.sql
src/main/java/de/imi/mopat/model/Encounter.java

Updated encounter controller property preselected_clinic_id -> clinic_id

Updated encounter controller property preselected_clinic_id -> clinic_id

---

src/main/webapp/WEB-INF/fragments/configurationTypes.html
src/main/webapp/WEB-INF/fragments/forms.html
src/main/webapp/WEB-INF/fragments/resourceFragment.html
src/main/webapp/WEB-INF/layout/main.html
src/main/webapp/WEB-INF/questionnaire/edit.html
src/main/webapp/js/helper/image.js

128 prevent svg file upload entirely
#128

128 prevent svg file upload entirely

---

src/main/java/de/imi/mopat/controller/ClinicController.java
src/main/java/de/imi/mopat/dao/EncounterDao.java
src/main/java/de/imi/mopat/dao/impl/EncounterDaoImpl.java
src/main/java/de/imi/mopat/model/Clinic.java
src/main/resources/message/messages.properties
src/main/resources/message/messages_de_DE.properties
src/main/resources/message/messages_en_GB.properties
src/main/webapp/WEB-INF/clinic/list.html

Updated clinic remove api to show a message for deletion failure

Updated clinic remove api to show a message for deletion failure

---

src/main/webapp/WEB-INF/question/edit.html

130 Slider Input attribute fixed

---

src/main/java/de/imi/mopat/controller/ClinicController.java

138 clinic configurations cannot be updated

---

src/main/java/de/imi/mopat/controller/ConditionController.java

Reworked the logic for inputs for question of type number checkbox and slider for min and max value validation
#157

157 reworked the logic for inputs for question of type number checkbox and slider

---

src/main/java/de/imi/mopat/helper/controller/HtmlUtils.java
src/main/java/de/imi/mopat/validator/BundleDTOValidator.java

Added a util classes to validate empty html based description
#165

165 bundle description is not validated

---

src/main/java/de/imi/mopat/controller/SurveyController.java
src/main/java/de/imi/mopat/helper/controller/HL7v22PatientInformationRetriever.java
src/main/java/de/imi/mopat/helper/controller/HL7v22PatientInformationRetrieverByPID.java

Null check for caseNumber and patientNumber for HL7 patient data retriever
#167

Null check for caseNumber and patientNumber for HL7 patient data retriever

---

src/main/java/de/imi/mopat/io/impl/MetadataExporterODMExportTemplate.java

Fix for odm export template having body part questions
resolves: #164

Fix for odm export template having body part questions

---

src/main/webapp/WEB-INF/mobile/survey/check.html

Fixed barcode scanner not activating the button after scan

---

src/main/java/de/imi/mopat/helper/controller/LocaleHelper.java
src/main/webapp/WEB-INF/bundle/list.html
src/main/webapp/WEB-INF/encounter/list.html
src/main/webapp/WEB-INF/invitation/list.html
src/main/webapp/WEB-INF/layout/main.html
src/main/webapp/WEB-INF/questionnaire/list.html

194 sorting by created at does not work after fixing the format
